/** Dat/spr signatures of known client files (generated by `npm run verify-packs -- --write-signatures`). */
export interface KnownSignature {
  version: number;
  dat: number;
  spr: number;
  /** Name of the data pack the signature was taken from. */
  pack: string;
}

export const KNOWN_SIGNATURES: readonly KnownSignature[] = [
  { version: 710, dat: 0x3dff4b2a, spr: 0x3dff4aeb, pack: '710' }, // v1
  { version: 713, dat: 0x3fd4fb91, spr: 0x3fd4fb5f, pack: '713' }, // v1
  { version: 721, dat: 0x3fdf40c6, spr: 0x3fdf408a, pack: '721' }, // v1
  { version: 723, dat: 0x404e1c14, spr: 0x4048e1ee, pack: '723' }, // v1
  { version: 724, dat: 0x404e1c14, spr: 0x4048e1ee, pack: '724' }, // v1
  { version: 726, dat: 0x404e1c14, spr: 0x4048e1ee, pack: '726' }, // v1
  { version: 727, dat: 0x404e1c14, spr: 0x4048e1ee, pack: '727' }, // v1
  { version: 730, dat: 0x411a6233, spr: 0x411a6279, pack: '730' }, // v1
  { version: 740, dat: 0x41bf619c, spr: 0x41b9ea86, pack: '740' }, // v2
  { version: 741, dat: 0x41bf619c, spr: 0x41b9ea86, pack: '741' }, // v2
  { version: 750, dat: 0x42f81973, spr: 0x42f81949, pack: '750' }, // v2
  { version: 760, dat: 0x439d5a33, spr: 0x439852be, pack: '760' }, // v3
  { version: 770, dat: 0x439d5a33, spr: 0x439852be, pack: '770' }, // v3
  { version: 772, dat: 0x439d5a33, spr: 0x439852be, pack: '772' }, // v3
  { version: 780, dat: 0x44ce4743, spr: 0x44ce4206, pack: '780' }, // v4
  { version: 781, dat: 0x44ce4743, spr: 0x44ce4206, pack: '781' }, // v4
  { version: 790, dat: 0x457d854e, spr: 0x457957c8, pack: '790' }, // v4
  { version: 792, dat: 0x459e7b73, spr: 0x45880fe8, pack: '792' }, // v4
  { version: 800, dat: 0x467fd7e6, spr: 0x467f9e74, pack: '800' }, // v4
  { version: 811, dat: 0x47f60e37, spr: 0x47ebb9b2, pack: '811' }, // v4
  { version: 820, dat: 0x486905aa, spr: 0x4868ecc9, pack: '820' }, // v4
  { version: 821, dat: 0x486cca2b, spr: 0x4868ecc9, pack: '821' }, // v4
  { version: 822, dat: 0x489980a1, spr: 0x489980a5, pack: '822' }, // v4
  { version: 830, dat: 0x48da1fb6, spr: 0x48c8e712, pack: '830' }, // v4
  { version: 831, dat: 0x48da1fb6, spr: 0x48c8e712, pack: '831' }, // v4
  { version: 840, dat: 0x493d607a, spr: 0x493d4e7c, pack: '840' }, // v4
  { version: 841, dat: 0x49b7cc19, spr: 0x49b140ea, pack: '841' }, // v4
  { version: 842, dat: 0x49c233c9, spr: 0x49b140ea, pack: '842' }, // v4
  { version: 850, dat: 0x4a49c5eb, spr: 0x4a44fd4e, pack: '850' }, // v4
  { version: 852, dat: 0x4a4cc0dc, spr: 0x4a44fd4e, pack: '852' }, // v4
  { version: 853, dat: 0x4ae97492, spr: 0x4acb5230, pack: '853' }, // v4
  { version: 854, dat: 0x4b1e2caa, spr: 0x4b1e2c87, pack: '854' }, // v4
  { version: 855, dat: 0x4b98ff53, spr: 0x4b913871, pack: '855' }, // v4
  { version: 856, dat: 0x4b98ff53, spr: 0x4b913871, pack: '856' }, // v4
  { version: 857, dat: 0x4b98ff53, spr: 0x4b913871, pack: '857' }, // v4
  { version: 860, dat: 0x4c28b721, spr: 0x4c220594, pack: '860' }, // v5
  { version: 860, dat: 0x4c2c7993, spr: 0x4c220594, pack: '860_old' }, // v5
  { version: 861, dat: 0x4c6a4cbc, spr: 0x4c63f145, pack: '861' }, // v5
  { version: 862, dat: 0x4c973450, spr: 0x4c63f145, pack: '862' }, // v5
  { version: 870, dat: 0x4cfe22c5, spr: 0x4cfd078a, pack: '870' }, // v5
  { version: 871, dat: 0x4d41979e, spr: 0x4d3d65d0, pack: '871' }, // v5
  { version: 900, dat: 0x4dbaa20b, spr: 0x4dad1a32, pack: '900' }, // v5
  { version: 910, dat: 0x4e12daff, spr: 0x4e12db27, pack: '910' }, // v5
  { version: 920, dat: 0x4e807c08, spr: 0x4e807c23, pack: '920' }, // v5
  { version: 931, dat: 0x4e807c08, spr: 0x4e807c23, pack: '931' }, // v5
  { version: 940, dat: 0x4ee71de5, spr: 0x4ee71e06, pack: '940' }, // v5
  { version: 941, dat: 0x4ee71de5, spr: 0x4ee71e06, pack: '941' }, // v5
  { version: 942, dat: 0x4ee71de5, spr: 0x4ee71e06, pack: '942' }, // v5
  { version: 943, dat: 0x4ee71de5, spr: 0x4ee71e06, pack: '943' }, // v5
  { version: 944, dat: 0x4f3131cf, spr: 0x4f3131f6, pack: '944' }, // v5
  { version: 946, dat: 0x4f6b341f, spr: 0x4f5dcef7, pack: '946' }, // v5
  { version: 952, dat: 0x4f857f6c, spr: 0x4f857f8e, pack: '952' }, // v5
  { version: 954, dat: 0x4fd5956b, spr: 0x4fd595b7, pack: '954' }, // v5
  { version: 960, dat: 0x4ffa74cc, spr: 0x4ffa74f9, pack: '960' }, // v5+ext
  { version: 970, dat: 0x5072a490, spr: 0x5072a567, pack: '970' }, // v5+ext
  { version: 971, dat: 0x5072a490, spr: 0x5072a567, pack: '971' }, // v5+ext
  { version: 980, dat: 0x50c70674, spr: 0x50c70753, pack: '980' }, // v5+ext
  { version: 981, dat: 0x50d1c5b6, spr: 0x50d1c685, pack: '981' }, // v5+ext
  { version: 1000, dat: 0x44ba, spr: 0x583d78e9, pack: '1000' }, // v6+ext+anim+groups
  { version: 1010, dat: 0x51e3f8c3, spr: 0x51e3f8e9, pack: '1010' }, // v6+ext
  { version: 1020, dat: 0x5236f129, spr: 0x5236f14f, pack: '1020' }, // v6+ext
  { version: 1035, dat: 0x52fdfc2c, spr: 0x52fdfc54, pack: '1035' }, // v6+ext
  { version: 1036, dat: 0x53159c7e, spr: 0x53159ca9, pack: '1036' }, // v6+ext
  { version: 1037, dat: 0x531ea82e, spr: 0x531ea856, pack: '1037' }, // v6+ext
  { version: 1038, dat: 0x5333c199, spr: 0x5333c1c3, pack: '1038' }, // v6+ext
  { version: 1041, dat: 0x5383504e, spr: 0x53835077, pack: '1041' }, // v6+ext
  { version: 1050, dat: 0x53b6460e, spr: 0x53b64639, pack: '1050' }, // v6+ext+anim
  { version: 1055, dat: 0x54128727, spr: 0x54128755, pack: '1055' }, // v6+ext+anim
  { version: 1057, dat: 0x542535f9, spr: 0x54253627, pack: '1057' }, // v6+ext+anim+groups
  { version: 1059, dat: 0x5434084b, spr: 0x54340879, pack: '1059' }, // v6+ext+anim+groups
  { version: 1061, dat: 0x5448d9c7, spr: 0x5448da10, pack: '1061' }, // v6+ext+anim+groups
  { version: 1063, dat: 0x546b502a, spr: 0x546b505e, pack: '1063' }, // v6+ext+anim+groups
  { version: 1064, dat: 0x547f05be, spr: 0x547f0632, pack: '1064' }, // v6+ext+anim+groups
  { version: 1070, dat: 0x5481bb97, spr: 0x5481bc06, pack: '1070' }, // v6+ext+anim+groups
  { version: 1071, dat: 0x334f, spr: 0x548e9efe, pack: '1071' }, // v6+ext+anim+groups
  { version: 1073, dat: 0x374d, spr: 0x54bc95ae, pack: '1073' }, // v6+ext+anim+groups
  { version: 1075, dat: 0x3775, spr: 0x54d85085, pack: '1075' }, // v6+ext+anim+groups
  { version: 1076, dat: 0x37df, spr: 0x54f03ce9, pack: '1076' }, // v6+ext+anim+groups
  { version: 1077, dat: 0x38de, spr: 0x5525213d, pack: '1077' }, // v6+ext+anim+groups
  { version: 1078, dat: 0x39cc, spr: 0x554c7373, pack: '1078' }, // v6+ext+anim+groups
  { version: 1079, dat: 0x3a71, spr: 0x557a5e34, pack: '1079' }, // v6+ext+anim+groups
  { version: 1080, dat: 0x3b1a, spr: 0x55a8be2e, pack: '1080' }, // v6+ext+anim+groups
  { version: 1081, dat: 0x3b74, spr: 0x55c49608, pack: '1081' }, // v6+ext+anim+groups
  { version: 1082, dat: 0x3c1d, spr: 0x5603c8b0, pack: '1082' }, // v6+ext+anim+groups
  { version: 1090, dat: 0x3f26, spr: 0x565ee171, pack: '1090' }, // v6+ext+anim+groups
  { version: 1091, dat: 0x3f81, spr: 0x56bc8198, pack: '1091' }, // v6+ext+anim+groups
  { version: 1092, dat: 0x4086, spr: 0x570742b8, pack: '1092' }, // v6+ext+anim+groups
  { version: 1093, dat: 0x413f, spr: 0x5726e657, pack: '1093' }, // v6+ext+anim+groups
  { version: 1094, dat: 0x41e5, spr: 0x57459d43, pack: '1094' }, // v6+ext+anim+groups
  { version: 1095, dat: 0x41f3, spr: 0x575a84bd, pack: '1095' }, // v6+ext+anim+groups
  { version: 1096, dat: 0x4243, spr: 0x577fa18e, pack: '1096' }, // v6+ext+anim+groups
  { version: 1097, dat: 0x42a3, spr: 0x57bbd603, pack: '1097' }, // v6+ext+anim+groups
  { version: 1098, dat: 0x42a3, spr: 0x57bbd603, pack: '1098' }, // v6+ext+anim+groups
  { version: 1099, dat: 0x4347, spr: 0x57ff106b, pack: '1099' }, // v6+ext+anim+groups
  { version: 1287, dat: 0x4a10, spr: 0x59e48e02, pack: '1287' }, // v6+ext+anim+groups
  { version: 1310, dat: 0x4a10, spr: 0x59e48e02, pack: '1310' }, // v6+ext+anim+groups
  { version: 1340, dat: 0x4a10, spr: 0x59e48e02, pack: '1340' }, // v6+ext+anim+groups
  { version: 1411, dat: 0x4a10, spr: 0x59e48e02, pack: '1411' }, // v6+ext+anim+groups
  { version: 1501, dat: 0x42a3, spr: 0x53159ca9, pack: '1501' }, // v6+ext+anim+groups
  { version: 1510, dat: 0x4a10, spr: 0x59e48e02, pack: '15.10.2daede' }, // v6+ext+anim+groups
];

/** Primary (first listed) signatures of a version. */
export function signatureFor(version: number): KnownSignature | undefined {
  return KNOWN_SIGNATURES.find((s) => s.version === version);
}
